# Generated by Django 4.2.5 on 2023-10-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rmbg_img',
            field=models.ImageField(blank=True, upload_to='images_rmbg'),
        ),
    ]
